config/routes.rb
SimpleTasking::Application.routes.draw do
  resources :columns do 
      resources :answers, :controller => 'Columns::Answers'
  end

  resources :checklists do 
    resources :tasks, :controller => 'Checklists::Tasks'
    get 'create_task'
    get 'create_column'    
  end
  

  resources :groups

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root :to => 'checklists#index'
end

app/models/checklist.rb
class Checklist
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :private, :type => Boolean, :default => false

  named_scope :for_user, lambda {|user| where(user_id: user.id) }

  named_scope :viewable_for, lambda {|user| any_of({:user_id => user.id},{:private.ne => true}) }

  belongs_to :user
  embeds_many :tasks, :class_name => "Checklists::Task"
  has_many :columns

  def can_modified_by(current_user)
    if user == current_user
      return true
    else
      #todo: group logic
      return false
    end
  end
end

app/models/checklists/task.rb
class Checklists::Task
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String

  embedded_in :checklist
  
  def html_description
    description.gsub('\n','<br />')
  end
end

app/controllers/checklists/tasks_controller.rb
class Checklists::TasksController < ApplicationController
  before_filter :load_checklist
  # GET /checklists/tasks
  # GET /checklists/tasks.json
  def index
    @checklists_tasks = @checklist.tasks.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checklists_tasks }
    end
  end

  # GET /checklists/tasks/1
  # GET /checklists/tasks/1.json
  def show
    @checklists_task = @checklist.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklists_task }
    end
  end

  # GET /checklists/tasks/new
  # GET /checklists/tasks/new.json
  def new
    @task = Checklists::Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /checklists/tasks/1/edit
  def edit
    @checklists_task = @checklist.tasks.find(params[:id])
  end

  # POST /checklists/tasks
  # POST /checklists/tasks.json
  def create
    @checklists_task = @checklist.tasks.new(params[:checklists_task])

    respond_to do |format|
      if @checklists_task.save
        format.html { redirect_to @checklists_task, notice: 'Task was successfully created.' }
        format.json { render json: @checklists_task, status: :created, location: @checklists_task }
      else
        format.html { render action: "new" }
        format.json { render json: @checklists_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklists/tasks/1
  # PUT /checklists/tasks/1.json
  def update
    @checklists_task = @checklist.tasks.find(params[:id])

    respond_to do |format|
      if @checklists_task.update_attributes(params[:checklists_task])
        format.html { redirect_to @checklists_task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklists_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/tasks/1
  # DELETE /checklists/tasks/1.json
  def destroy
    @checklists_task = @checklist.tasks.find(params[:id])
    @checklists_task.destroy

    respond_to do |format|
      format.html { redirect_to checklists_tasks_url }
      format.json { head :no_content }
    end
  end

  private
  def load_checklist
    @checklist = Checklist.find(params[:checklist_id])
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_filter :authenticate_user!

  # GET /checklists
  # GET /checklists.json
  def index
    @my_checklists = Checklist.for_user(current_user).all

    @public_checklists = Checklist.viewable_for(current_user).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checklists }
    end
  end

  # GET /checklists/1
  # GET /checklists/1.json
  def show
    @checklist = Checklist.find(params[:id])
    @checklist.columns.for_user(current_user).create(:user_id=>current_user.id,:name=>"Untitled Column") if @checklist.columns.for_user(current_user).length == 0
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/new
  # GET /checklists/new.json
  def new
    @checklist = Checklist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/1/edit
  def edit
    @checklist = Checklist.find(params[:id])
  end

  # POST /checklists
  # POST /checklists.json
  def create
    @checklist = Checklist.new(params[:checklist])
    @checklist.user = current_user
    respond_to do |format|
      if @checklist.save
        format.html { redirect_to @checklist, notice: 'Checklist was successfully created.' }
        format.json { render json: @checklist, status: :created, location: @checklist }
      else
        format.html { render action: "new" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklists/1
  # PUT /checklists/1.json
  def update
    @checklist = Checklist.find(params[:id])

    respond_to do |format|
      if @checklist.update_attributes(params[:checklist])
        format.html { redirect_to @checklist, notice: 'Checklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/1
  # DELETE /checklists/1.json
  def destroy
    @checklist = Checklist.find(params[:id])
    @checklist.destroy

    respond_to do |format|
      format.html { redirect_to checklists_url }
      format.json { head :no_content }
    end
  end

  def create_task
    @checklist = Checklist.find(params[:checklist_id])
    @checklist.tasks.create(name: "New Task", description: "Description for task")
    redirect_to checklist_path(@checklist)
  end

  def create_column
    @checklist = Checklist.find(params[:checklist_id])
    @checklist.columns.create(name: "New Column", user_id: current_user.id)
    redirect_to checklist_path(@checklist)
  end
end

app/helpers/checklist/tasks_helper.rb
module Checklist::TasksHelper
end

app/helpers/checklists/tasks_helper.rb
module Checklists::TasksHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
  def add_edit_icon(d)
    d + '<i class="icon-pencil"></i>'.html_safe 
  end
end

app/views/checklists/tasks/_form.html.erb
<%= simple_form_for(@task,:url => checklist_task_path(@checklist)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checklists/tasks/_form.text.erb
<%= simple_form_for(@task,:url => checklist_task_path(@checklist)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checklists/tasks/edit.html.erb
<h1>Editing checklists_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @checklists_task %> |
<%= link_to 'Back', checklists_tasks_path %>

app/views/checklists/tasks/index.html.erb
<h1>Listing checklists_tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checklists_tasks.each do |checklists_task| %>
  <tr>
    <td><%= checklists_task.name %></td>
    <td><%= checklists_task.description %></td>
    <td><%= link_to 'Show', checklists_task %></td>
    <td><%= link_to 'Edit', edit_checklists_task_path(checklists_task) %></td>
    <td><%= link_to 'Destroy', checklists_task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_checklists_task_path %>

app/views/checklists/tasks/new.html.erb
<h1>New checklists_task</h1>

<%= render 'form' %>

<%= link_to 'Back', checklists_tasks_path %>

app/views/checklists/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @checklists_task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @checklists_task.description %>
</p>


<%= link_to 'Edit', edit_checklists_task_path(@checklists_task) %> |
<%= link_to 'Back', checklists_tasks_path %>