config/routes.rb
SimpleTasking::Application.routes.draw do
  resources :columns do 
      resources :answers, :controller => 'Columns::Answers'
  end

  resources :checklists do 
    resources :tasks, :controller => 'Checklists::Tasks'
    get 'create_task'
    get 'create_column'    
  end
  

  resources :groups

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root :to => 'checklists#index'
end

app/models/column.rb
class Column
  include Mongoid::Document
  field :name, :type => String
  field :pos, :type => Integer
  field :private, :type => Boolean, :default => false
  include ActsAsList::Mongoid 
  acts_as_list :column => :pos
  
  
  belongs_to :checklist
  belongs_to :user
  embeds_many :answers, :class_name => 'Columns::Answer'

  named_scope :for_user, lambda {|user| where(user_id: user.id) }


end

app/models/columns/answer.rb
class Columns::Answer
  include Mongoid::Document
  field :flag, :type => Integer, :default=> 0
  field :task_id, :type => String

  belongs_to :user
  embedded_in :column

  def image
    image_loc = '/assets/tick-off.png'
    case flag
    when 0
      image_loc = '/assets/tick-off.png'
    when 1
      image_loc = '/assets/tick-on.png'
    when 2
      image_loc = '/assets/na.png'
    end
    image_loc
  end
end

app/controllers/columns/answers_controller.rb
class Columns::AnswersController < ApplicationController
  before_filter :load_column
  def update
    @columns_answer = @column.answers.find(params[:id])
    @columns_answer.flag = params[:flag]
    @columns_answer.flag = 0 if !@columns_answer.flag || @columns_answer.flag > 2 || @columns_answer.flag <0
    @columns_answer.save

    render :json=>@columns_answer.image
  end

  def load_column
    @column = Column.find(params[:column_id])
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_filter :authenticate_user!

  # GET /columns
  # GET /columns.json
  def index
    @columns = Column.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @columns }
    end
  end

  # GET /columns/1
  # GET /columns/1.json
  def show
    @column = Column.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @column }
    end
  end

  # GET /columns/new
  # GET /columns/new.json
  def new
    @column = Column.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @column }
    end
  end

  # GET /columns/1/edit
  def edit
    @column = Column.find(params[:id])
  end

  # POST /columns
  # POST /columns.json
  def create
    @column = Column.new(params[:column])

    respond_to do |format|
      if @column.save
        format.html { redirect_to @column, notice: 'Column was successfully created.' }
        format.json { render json: @column, status: :created, location: @column }
      else
        format.html { render action: "new" }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /columns/1
  # PUT /columns/1.json
  def update
    @column = Column.find(params[:id])

    respond_to do |format|
      if @column.update_attributes(params[:column])
        format.html { redirect_to @column, notice: 'Column was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columns/1
  # DELETE /columns/1.json
  def destroy
    @column = Column.find(params[:id])
    @column.destroy

    respond_to do |format|
      format.html { redirect_to columns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/columns/answers_helper.rb
module Columns::AnswersHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/_form.html.erb
<%= simple_form_for(@column) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :pos %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing column</h1>

<%= render 'form' %>

<%= link_to 'Show', @column %> |
<%= link_to 'Back', columns_path %>

app/views/columns/index.html.erb
<h1>Listing columns</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @columns.each do |column| %>
  <tr>
    <td><%= column.name %></td>
    <td><%= column.pos %></td>
    <td><%= link_to 'Show', column %></td>
    <td><%= link_to 'Edit', edit_column_path(column) %></td>
    <td><%= link_to 'Destroy', column, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Column', new_column_path %>

app/views/columns/new.html.erb
<h1>New column</h1>

<%= render 'form' %>

<%= link_to 'Back', columns_path %>

app/views/columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @column.name %>
</p>

<p>
  <b>Pos:</b>
  <%= @column.pos %>
</p>


<%= link_to 'Edit', edit_column_path(@column) %> |
<%= link_to 'Back', columns_path %>