config/routes.rb
SimpleTasking::Application.routes.draw do
  resources :columns do 
      resources :answers, :controller => 'Columns::Answers'
  end

  resources :checklists do 
    resources :tasks, :controller => 'Checklists::Tasks'
    get 'create_task'
    get 'create_column'    
  end
  

  resources :groups

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root :to => 'checklists#index'
end

app/models/checklist.rb
class Checklist
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :private, :type => Boolean, :default => false

  named_scope :for_user, lambda {|user| where(user_id: user.id) }

  named_scope :viewable_for, lambda {|user| any_of({:user_id => user.id},{:private.ne => true}) }

  belongs_to :user
  embeds_many :tasks, :class_name => "Checklists::Task"
  has_many :columns

  def can_modified_by(current_user)
    if user == current_user
      return true
    else
      #todo: group logic
      return false
    end
  end
end

app/models/checklists/task.rb
class Checklists::Task
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String

  embedded_in :checklist
  
  def html_description
    description.gsub('\n','<br />')
  end
end

app/controllers/checklists/tasks_controller.rb
class Checklists::TasksController < ApplicationController
  before_filter :load_checklist
  # GET /checklists/tasks
  # GET /checklists/tasks.json
  def index
    @checklists_tasks = @checklist.tasks.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checklists_tasks }
    end
  end

  # GET /checklists/tasks/1
  # GET /checklists/tasks/1.json
  def show
    @checklists_task = @checklist.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklists_task }
    end
  end

  # GET /checklists/tasks/new
  # GET /checklists/tasks/new.json
  def new
    @task = Checklists::Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /checklists/tasks/1/edit
  def edit
    @checklists_task = @checklist.tasks.find(params[:id])
  end

  # POST /checklists/tasks
  # POST /checklists/tasks.json
  def create
    @checklists_task = @checklist.tasks.new(params[:checklists_task])

    respond_to do |format|
      if @checklists_task.save
        format.html { redirect_to @checklists_task, notice: 'Task was successfully created.' }
        format.json { render json: @checklists_task, status: :created, location: @checklists_task }
      else
        format.html { render action: "new" }
        format.json { render json: @checklists_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklists/tasks/1
  # PUT /checklists/tasks/1.json
  def update
    @checklists_task = @checklist.tasks.find(params[:id])

    respond_to do |format|
      if @checklists_task.update_attributes(params[:checklists_task])
        format.html { redirect_to @checklists_task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklists_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/tasks/1
  # DELETE /checklists/tasks/1.json
  def destroy
    @checklists_task = @checklist.tasks.find(params[:id])
    @checklists_task.destroy

    respond_to do |format|
      format.html { redirect_to checklists_tasks_url }
      format.json { head :no_content }
    end
  end

  private
  def load_checklist
    @checklist = Checklist.find(params[:checklist_id])
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_filter :authenticate_user!

  # GET /checklists
  # GET /checklists.json
  def index
    @my_checklists = Checklist.for_user(current_user).all

    @public_checklists = Checklist.viewable_for(current_user).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checklists }
    end
  end

  # GET /checklists/1
  # GET /checklists/1.json
  def show
    @checklist = Checklist.find(params[:id])
    @checklist.columns.for_user(current_user).create(:user_id=>current_user.id,:name=>"Untitled Column") if @checklist.columns.for_user(current_user).length == 0
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/new
  # GET /checklists/new.json
  def new
    @checklist = Checklist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/1/edit
  def edit
    @checklist = Checklist.find(params[:id])
  end

  # POST /checklists
  # POST /checklists.json
  def create
    @checklist = Checklist.new(params[:checklist])
    @checklist.user = current_user
    respond_to do |format|
      if @checklist.save
        format.html { redirect_to @checklist, notice: 'Checklist was successfully created.' }
        format.json { render json: @checklist, status: :created, location: @checklist }
      else
        format.html { render action: "new" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklists/1
  # PUT /checklists/1.json
  def update
    @checklist = Checklist.find(params[:id])

    respond_to do |format|
      if @checklist.update_attributes(params[:checklist])
        format.html { redirect_to @checklist, notice: 'Checklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/1
  # DELETE /checklists/1.json
  def destroy
    @checklist = Checklist.find(params[:id])
    @checklist.destroy

    respond_to do |format|
      format.html { redirect_to checklists_url }
      format.json { head :no_content }
    end
  end

  def create_task
    @checklist = Checklist.find(params[:checklist_id])
    @checklist.tasks.create(name: "New Task", description: "Description for task")
    redirect_to checklist_path(@checklist)
  end

  def create_column
    @checklist = Checklist.find(params[:checklist_id])
    @checklist.columns.create(name: "New Column", user_id: current_user.id)
    redirect_to checklist_path(@checklist)
  end
end

app/helpers/checklist/tasks_helper.rb
module Checklist::TasksHelper
end

app/helpers/checklists/tasks_helper.rb
module Checklists::TasksHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
  def add_edit_icon(d)
    d + '<i class="icon-pencil"></i>'.html_safe 
  end
end

app/views/checklists/_column.html.erb
<div class="column_row">
  <div class="column column-header">
    <div class="column-name" data-icon-width="30px">
     <%= best_in_place column, :name, :type => :input, :path => column_path(column) %>
    </div>
  </div>
<%column.checklist.tasks.each do |task|%>
  <div class="column" data-task="<%=task.id%>">
    <div class="column-items">
      <%answer = column.answers.find_or_create_by(:task_id=> task.id)%>
      <img src="<%=answer.image%>" width= '30px' height= '30px' class="check-icons" data-answer="<%=answer.id%>" data-column="<%=column.id%>" data-flag="<%=answer.flag%>">
    </div>
  </div>
<%end%>
</div>

app/views/checklists/_form.html.erb
<div class="signup_form">
  <%= form_for(@checklist) do |f| %>
    <div><%= f.label :name %>
    <%= f.text_field :name %></div>

    <div><%= f.label :description %>
    <%= f.text_field :description %></div>

  <div class="form-remember">
    <%= f.check_box :private %> <%= f.label :private %>
</div>
    <div><%= f.button :Create,class: 'btn btn-primary' %></div>
  <% end %>
</div>

app/views/checklists/_task.html.erb
<div class="task_item" data-task="<%=task.id%>">
<p>
  <%if @checklist.user == current_user%>
    <%= best_in_place task, :name, :type => :input, :path => checklist_task_path(@checklist,task) %>
  <%else%>
    <%=task.name%>
  <%end%>
 </p>

</div>

app/views/checklists/edit.html.erb
<h1>Editing checklist</h1>

<%= render 'form' %>

<%= link_to 'Show', @checklist %> |
<%= link_to 'Back', checklists_path %>

app/views/checklists/index.html.erb
<div class="headline">
 	<h1>Checklists to bang!</h1>       
</div>

<div>
  <ul class="setting_box">
  <li><h2>My Checklists</h2></li>
  <% @my_checklists.each do |checklist| %>
    <li class="setting_col">
      <%=image_tag('/assets/lock.png',width: '20px',alt:"Private",title:"Private") if checklist.private%>
      <%=image_tag('/assets/unlock.png',width: '20px',alt:"Public",title:"Public") if !checklist.private%>
      <%= link_to checklist.name, checklist %>
      <span>
        <%= checklist.description %>
      </span>
    </li>
  <% end %>
  <li><%= link_to 'New Checklist', new_checklist_path, {:class=>"btn btn-success"} %></li>
</ul>
</div>

<div>

<ul class="setting_box">
<li><h2>Public Checklists</h2></li>
<% @public_checklists.each do |checklist| %>
  <li class="setting_col">
      <%=image_tag('/assets/lock.png',width: '20px',alt:"Private",title:"Private") if checklist.private%>
      <%=image_tag('/assets/unlock.png',width: '20px',alt:"Public",title:"Public") if !checklist.private%>
    <%= link_to checklist.name, checklist %> <em>by <%= checklist.user.email.split('@').first %></em>
    <span>
      <%= checklist.description %>
    </span>
  </li>
<% end %>
</ul>
</div>

app/views/checklists/new.html.erb
<div class="headline">
 	<h1>New Checklist</h1>
</div>


<%= render 'form' %>

app/views/checklists/show.html.erb
<div class="hero-unit">
  <%if @checklist.user == current_user%>
    <div style="float:right;margin-top:10px;" data-icon-width="50px">
    <%= best_in_place @checklist, :private, :type=>:checkbox, :collection => ['public','private'] %>
    </div>
  <%end%>
  <%if @checklist.user == current_user%>
    <h1><%= best_in_place @checklist, :name  %></h1>
  <%else%>
    <h1><%= @checklist.name %></h1>
  <%end%>
  <%if @checklist.user == current_user%>
    <span class="desc"><%= best_in_place @checklist, :description  %></span>
  <%else%>
    <span class="desc"><%= @checklist.description %></span>
  <%end%>
</div>

<!--/Task Bar-->
<div class="task section">
    <div class="task_item" style="background:none">
    </div>
  <%=render :partial => 'task', :collection=> @checklist.tasks %>

  <% if @checklist.can_modified_by(current_user) %>
    <div class="task_item add_new">
      <p><%=link_to image_tag('/assets/add.png',width:'30px') + "Add New Task",checklist_create_task_path(@checklist)%></p>
    </div>
  <% end %>

</div>

<div class="columns section">
  <div class="column_container">
    <%=render :partial => 'column', :collection=> @checklist.columns.for_user(current_user) %>
    <!--/Add list Bar-->
    <div class="addcolumn section">
      <%=link_to image_tag('/assets/add.png',width:'45px'),checklist_create_column_path(@checklist)%>
    </div>
  </div>

</div>